GIT_HASH: 791a61f
[1m============================= test session starts ==============================[0m
platform darwin -- Python 3.6.4, pytest-3.5.0, py-1.5.3, pluggy-0.6.0
rootdir: /Users/drapp/sandbox/redblackgraph, inifile:
plugins: cov-2.5.1
collected 0 items / 11 errors

==================================== ERRORS ====================================
____________________ ERROR collecting tests/test_einsum.py _____________________
[31mImportError while importing test module '/Users/drapp/sandbox/redblackgraph/tests/test_einsum.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
redblackgraph/core/__init__.py:6: in <module>
    from .. import rb_multiarray
E   ImportError: dlopen(/Users/drapp/sandbox/redblackgraph/redblackgraph/rb_multiarray.cpython-36m-darwin.so, 2): Symbol not found: _int_avos
E     Referenced from: /Users/drapp/sandbox/redblackgraph/redblackgraph/rb_multiarray.cpython-36m-darwin.so
E     Expected in: flat namespace
E    in /Users/drapp/sandbox/redblackgraph/redblackgraph/rb_multiarray.cpython-36m-darwin.so

During handling of the above exception, another exception occurred:
tests/test_einsum.py:2: in <module>
    from redblackgraph import einsum, avos_sum, avos_product
redblackgraph/__init__.py:6: in <module>
    from . import core
redblackgraph/core/__init__.py:17: in <module>
    raise ImportError(msg)
E   ImportError: 
E   Importing the multiarray redblackgraph extension module failed.  Most
E   likely you are trying to import a failed build of redblackgraph.
E   If you're working with a git repo, try `git clean -xdf` (removes all
E   files not under version control).  Otherwise reinstall redblackgraph.
E   
E   Original error was: dlopen(/Users/drapp/sandbox/redblackgraph/redblackgraph/rb_multiarray.cpython-36m-darwin.so, 2): Symbol not found: _int_avos
E     Referenced from: /Users/drapp/sandbox/redblackgraph/redblackgraph/rb_multiarray.cpython-36m-darwin.so
E     Expected in: flat namespace
E    in /Users/drapp/sandbox/redblackgraph/redblackgraph/rb_multiarray.cpython-36m-darwin.so[0m
_____________________ ERROR collecting tests/test_loops.py _____________________
[31mImportError while importing test module '/Users/drapp/sandbox/redblackgraph/tests/test_loops.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
redblackgraph/core/__init__.py:6: in <module>
    from .. import rb_multiarray
E   ImportError: dlopen(/Users/drapp/sandbox/redblackgraph/redblackgraph/rb_multiarray.cpython-36m-darwin.so, 2): Symbol not found: _int_avos
E     Referenced from: /Users/drapp/sandbox/redblackgraph/redblackgraph/rb_multiarray.cpython-36m-darwin.so
E     Expected in: flat namespace
E    in /Users/drapp/sandbox/redblackgraph/redblackgraph/rb_multiarray.cpython-36m-darwin.so

During handling of the above exception, another exception occurred:
tests/test_loops.py:2: in <module>
    import redblackgraph as rb
redblackgraph/__init__.py:6: in <module>
    from . import core
redblackgraph/core/__init__.py:17: in <module>
    raise ImportError(msg)
E   ImportError: 
E   Importing the multiarray redblackgraph extension module failed.  Most
E   likely you are trying to import a failed build of redblackgraph.
E   If you're working with a git repo, try `git clean -xdf` (removes all
E   files not under version control).  Otherwise reinstall redblackgraph.
E   
E   Original error was: dlopen(/Users/drapp/sandbox/redblackgraph/redblackgraph/rb_multiarray.cpython-36m-darwin.so, 2): Symbol not found: _int_avos
E     Referenced from: /Users/drapp/sandbox/redblackgraph/redblackgraph/rb_multiarray.cpython-36m-darwin.so
E     Expected in: flat namespace
E    in /Users/drapp/sandbox/redblackgraph/redblackgraph/rb_multiarray.cpython-36m-darwin.so[0m
___________________ ERROR collecting tests/test_redblack.py ____________________
[31mImportError while importing test module '/Users/drapp/sandbox/redblackgraph/tests/test_redblack.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
redblackgraph/core/__init__.py:6: in <module>
    from .. import rb_multiarray
E   ImportError: dlopen(/Users/drapp/sandbox/redblackgraph/redblackgraph/rb_multiarray.cpython-36m-darwin.so, 2): Symbol not found: _int_avos
E     Referenced from: /Users/drapp/sandbox/redblackgraph/redblackgraph/rb_multiarray.cpython-36m-darwin.so
E     Expected in: flat namespace
E    in /Users/drapp/sandbox/redblackgraph/redblackgraph/rb_multiarray.cpython-36m-darwin.so

During handling of the above exception, another exception occurred:
tests/test_redblack.py:2: in <module>
    import redblackgraph as rb
redblackgraph/__init__.py:6: in <module>
    from . import core
redblackgraph/core/__init__.py:17: in <module>
    raise ImportError(msg)
E   ImportError: 
E   Importing the multiarray redblackgraph extension module failed.  Most
E   likely you are trying to import a failed build of redblackgraph.
E   If you're working with a git repo, try `git clean -xdf` (removes all
E   files not under version control).  Otherwise reinstall redblackgraph.
E   
E   Original error was: dlopen(/Users/drapp/sandbox/redblackgraph/redblackgraph/rb_multiarray.cpython-36m-darwin.so, 2): Symbol not found: _int_avos
E     Referenced from: /Users/drapp/sandbox/redblackgraph/redblackgraph/rb_multiarray.cpython-36m-darwin.so
E     Expected in: flat namespace
E    in /Users/drapp/sandbox/redblackgraph/redblackgraph/rb_multiarray.cpython-36m-darwin.so[0m
________________ ERROR collecting tests/reference/test_avos.py _________________
[31mImportError while importing test module '/Users/drapp/sandbox/redblackgraph/tests/reference/test_avos.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
redblackgraph/core/__init__.py:6: in <module>
    from .. import rb_multiarray
E   ImportError: dlopen(/Users/drapp/sandbox/redblackgraph/redblackgraph/rb_multiarray.cpython-36m-darwin.so, 2): Symbol not found: _int_avos
E     Referenced from: /Users/drapp/sandbox/redblackgraph/redblackgraph/rb_multiarray.cpython-36m-darwin.so
E     Expected in: flat namespace
E    in /Users/drapp/sandbox/redblackgraph/redblackgraph/rb_multiarray.cpython-36m-darwin.so

During handling of the above exception, another exception occurred:
tests/reference/test_avos.py:1: in <module>
    from redblackgraph.reference.avos import avos_product, avos_sum, compute_sign
redblackgraph/__init__.py:6: in <module>
    from . import core
redblackgraph/core/__init__.py:17: in <module>
    raise ImportError(msg)
E   ImportError: 
E   Importing the multiarray redblackgraph extension module failed.  Most
E   likely you are trying to import a failed build of redblackgraph.
E   If you're working with a git repo, try `git clean -xdf` (removes all
E   files not under version control).  Otherwise reinstall redblackgraph.
E   
E   Original error was: dlopen(/Users/drapp/sandbox/redblackgraph/redblackgraph/rb_multiarray.cpython-36m-darwin.so, 2): Symbol not found: _int_avos
E     Referenced from: /Users/drapp/sandbox/redblackgraph/redblackgraph/rb_multiarray.cpython-36m-darwin.so
E     Expected in: flat namespace
E    in /Users/drapp/sandbox/redblackgraph/redblackgraph/rb_multiarray.cpython-36m-darwin.so[0m
__________ ERROR collecting tests/reference/test_calc_relationship.py __________
[31mImportError while importing test module '/Users/drapp/sandbox/redblackgraph/tests/reference/test_calc_relationship.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
redblackgraph/core/__init__.py:6: in <module>
    from .. import rb_multiarray
E   ImportError: dlopen(/Users/drapp/sandbox/redblackgraph/redblackgraph/rb_multiarray.cpython-36m-darwin.so, 2): Symbol not found: _int_avos
E     Referenced from: /Users/drapp/sandbox/redblackgraph/redblackgraph/rb_multiarray.cpython-36m-darwin.so
E     Expected in: flat namespace
E    in /Users/drapp/sandbox/redblackgraph/redblackgraph/rb_multiarray.cpython-36m-darwin.so

During handling of the above exception, another exception occurred:
tests/reference/test_calc_relationship.py:1: in <module>
    from redblackgraph.reference import calculate_relationship, Relationship
redblackgraph/__init__.py:6: in <module>
    from . import core
redblackgraph/core/__init__.py:17: in <module>
    raise ImportError(msg)
E   ImportError: 
E   Importing the multiarray redblackgraph extension module failed.  Most
E   likely you are trying to import a failed build of redblackgraph.
E   If you're working with a git repo, try `git clean -xdf` (removes all
E   files not under version control).  Otherwise reinstall redblackgraph.
E   
E   Original error was: dlopen(/Users/drapp/sandbox/redblackgraph/redblackgraph/rb_multiarray.cpython-36m-darwin.so, 2): Symbol not found: _int_avos
E     Referenced from: /Users/drapp/sandbox/redblackgraph/redblackgraph/rb_multiarray.cpython-36m-darwin.so
E     Expected in: flat namespace
E    in /Users/drapp/sandbox/redblackgraph/redblackgraph/rb_multiarray.cpython-36m-darwin.so[0m
_____________ ERROR collecting tests/reference/test_components.py ______________
[31mImportError while importing test module '/Users/drapp/sandbox/redblackgraph/tests/reference/test_components.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
redblackgraph/core/__init__.py:6: in <module>
    from .. import rb_multiarray
E   ImportError: dlopen(/Users/drapp/sandbox/redblackgraph/redblackgraph/rb_multiarray.cpython-36m-darwin.so, 2): Symbol not found: _int_avos
E     Referenced from: /Users/drapp/sandbox/redblackgraph/redblackgraph/rb_multiarray.cpython-36m-darwin.so
E     Expected in: flat namespace
E    in /Users/drapp/sandbox/redblackgraph/redblackgraph/rb_multiarray.cpython-36m-darwin.so

During handling of the above exception, another exception occurred:
tests/reference/test_components.py:2: in <module>
    from redblackgraph.reference import find_components, find_components_extended, triangularize, warshall
redblackgraph/__init__.py:6: in <module>
    from . import core
redblackgraph/core/__init__.py:17: in <module>
    raise ImportError(msg)
E   ImportError: 
E   Importing the multiarray redblackgraph extension module failed.  Most
E   likely you are trying to import a failed build of redblackgraph.
E   If you're working with a git repo, try `git clean -xdf` (removes all
E   files not under version control).  Otherwise reinstall redblackgraph.
E   
E   Original error was: dlopen(/Users/drapp/sandbox/redblackgraph/redblackgraph/rb_multiarray.cpython-36m-darwin.so, 2): Symbol not found: _int_avos
E     Referenced from: /Users/drapp/sandbox/redblackgraph/redblackgraph/rb_multiarray.cpython-36m-darwin.so
E     Expected in: flat namespace
E    in /Users/drapp/sandbox/redblackgraph/redblackgraph/rb_multiarray.cpython-36m-darwin.so[0m
______________ ERROR collecting tests/reference/test_mat_avos.py _______________
[31mImportError while importing test module '/Users/drapp/sandbox/redblackgraph/tests/reference/test_mat_avos.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
redblackgraph/core/__init__.py:6: in <module>
    from .. import rb_multiarray
E   ImportError: dlopen(/Users/drapp/sandbox/redblackgraph/redblackgraph/rb_multiarray.cpython-36m-darwin.so, 2): Symbol not found: _int_avos
E     Referenced from: /Users/drapp/sandbox/redblackgraph/redblackgraph/rb_multiarray.cpython-36m-darwin.so
E     Expected in: flat namespace
E    in /Users/drapp/sandbox/redblackgraph/redblackgraph/rb_multiarray.cpython-36m-darwin.so

During handling of the above exception, another exception occurred:
tests/reference/test_mat_avos.py:1: in <module>
    from redblackgraph.reference import mat_avos
redblackgraph/__init__.py:6: in <module>
    from . import core
redblackgraph/core/__init__.py:17: in <module>
    raise ImportError(msg)
E   ImportError: 
E   Importing the multiarray redblackgraph extension module failed.  Most
E   likely you are trying to import a failed build of redblackgraph.
E   If you're working with a git repo, try `git clean -xdf` (removes all
E   files not under version control).  Otherwise reinstall redblackgraph.
E   
E   Original error was: dlopen(/Users/drapp/sandbox/redblackgraph/redblackgraph/rb_multiarray.cpython-36m-darwin.so, 2): Symbol not found: _int_avos
E     Referenced from: /Users/drapp/sandbox/redblackgraph/redblackgraph/rb_multiarray.cpython-36m-darwin.so
E     Expected in: flat namespace
E    in /Users/drapp/sandbox/redblackgraph/redblackgraph/rb_multiarray.cpython-36m-darwin.so[0m
___________ ERROR collecting tests/reference/test_rel_composition.py ___________
[31mImportError while importing test module '/Users/drapp/sandbox/redblackgraph/tests/reference/test_rel_composition.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
redblackgraph/core/__init__.py:6: in <module>
    from .. import rb_multiarray
E   ImportError: dlopen(/Users/drapp/sandbox/redblackgraph/redblackgraph/rb_multiarray.cpython-36m-darwin.so, 2): Symbol not found: _int_avos
E     Referenced from: /Users/drapp/sandbox/redblackgraph/redblackgraph/rb_multiarray.cpython-36m-darwin.so
E     Expected in: flat namespace
E    in /Users/drapp/sandbox/redblackgraph/redblackgraph/rb_multiarray.cpython-36m-darwin.so

During handling of the above exception, another exception occurred:
tests/reference/test_rel_composition.py:1: in <module>
    from redblackgraph.reference import vertex_relational_composition, edge_relational_composition, warshall
redblackgraph/__init__.py:6: in <module>
    from . import core
redblackgraph/core/__init__.py:17: in <module>
    raise ImportError(msg)
E   ImportError: 
E   Importing the multiarray redblackgraph extension module failed.  Most
E   likely you are trying to import a failed build of redblackgraph.
E   If you're working with a git repo, try `git clean -xdf` (removes all
E   files not under version control).  Otherwise reinstall redblackgraph.
E   
E   Original error was: dlopen(/Users/drapp/sandbox/redblackgraph/redblackgraph/rb_multiarray.cpython-36m-darwin.so, 2): Symbol not found: _int_avos
E     Referenced from: /Users/drapp/sandbox/redblackgraph/redblackgraph/rb_multiarray.cpython-36m-darwin.so
E     Expected in: flat namespace
E    in /Users/drapp/sandbox/redblackgraph/redblackgraph/rb_multiarray.cpython-36m-darwin.so[0m
______________ ERROR collecting tests/reference/test_vec_avos.py _______________
[31mImportError while importing test module '/Users/drapp/sandbox/redblackgraph/tests/reference/test_vec_avos.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
redblackgraph/core/__init__.py:6: in <module>
    from .. import rb_multiarray
E   ImportError: dlopen(/Users/drapp/sandbox/redblackgraph/redblackgraph/rb_multiarray.cpython-36m-darwin.so, 2): Symbol not found: _int_avos
E     Referenced from: /Users/drapp/sandbox/redblackgraph/redblackgraph/rb_multiarray.cpython-36m-darwin.so
E     Expected in: flat namespace
E    in /Users/drapp/sandbox/redblackgraph/redblackgraph/rb_multiarray.cpython-36m-darwin.so

During handling of the above exception, another exception occurred:
tests/reference/test_vec_avos.py:1: in <module>
    from redblackgraph.reference import vec_avos
redblackgraph/__init__.py:6: in <module>
    from . import core
redblackgraph/core/__init__.py:17: in <module>
    raise ImportError(msg)
E   ImportError: 
E   Importing the multiarray redblackgraph extension module failed.  Most
E   likely you are trying to import a failed build of redblackgraph.
E   If you're working with a git repo, try `git clean -xdf` (removes all
E   files not under version control).  Otherwise reinstall redblackgraph.
E   
E   Original error was: dlopen(/Users/drapp/sandbox/redblackgraph/redblackgraph/rb_multiarray.cpython-36m-darwin.so, 2): Symbol not found: _int_avos
E     Referenced from: /Users/drapp/sandbox/redblackgraph/redblackgraph/rb_multiarray.cpython-36m-darwin.so
E     Expected in: flat namespace
E    in /Users/drapp/sandbox/redblackgraph/redblackgraph/rb_multiarray.cpython-36m-darwin.so[0m
______________ ERROR collecting tests/reference/test_warshall.py _______________
[31mImportError while importing test module '/Users/drapp/sandbox/redblackgraph/tests/reference/test_warshall.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
redblackgraph/core/__init__.py:6: in <module>
    from .. import rb_multiarray
E   ImportError: dlopen(/Users/drapp/sandbox/redblackgraph/redblackgraph/rb_multiarray.cpython-36m-darwin.so, 2): Symbol not found: _int_avos
E     Referenced from: /Users/drapp/sandbox/redblackgraph/redblackgraph/rb_multiarray.cpython-36m-darwin.so
E     Expected in: flat namespace
E    in /Users/drapp/sandbox/redblackgraph/redblackgraph/rb_multiarray.cpython-36m-darwin.so

During handling of the above exception, another exception occurred:
tests/reference/test_warshall.py:1: in <module>
    from redblackgraph.reference import warshall
redblackgraph/__init__.py:6: in <module>
    from . import core
redblackgraph/core/__init__.py:17: in <module>
    raise ImportError(msg)
E   ImportError: 
E   Importing the multiarray redblackgraph extension module failed.  Most
E   likely you are trying to import a failed build of redblackgraph.
E   If you're working with a git repo, try `git clean -xdf` (removes all
E   files not under version control).  Otherwise reinstall redblackgraph.
E   
E   Original error was: dlopen(/Users/drapp/sandbox/redblackgraph/redblackgraph/rb_multiarray.cpython-36m-darwin.so, 2): Symbol not found: _int_avos
E     Referenced from: /Users/drapp/sandbox/redblackgraph/redblackgraph/rb_multiarray.cpython-36m-darwin.so
E     Expected in: flat namespace
E    in /Users/drapp/sandbox/redblackgraph/redblackgraph/rb_multiarray.cpython-36m-darwin.so[0m
___________ ERROR collecting tests/util/test_relationship_file_io.py ___________
[31mImportError while importing test module '/Users/drapp/sandbox/redblackgraph/tests/util/test_relationship_file_io.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
redblackgraph/core/__init__.py:6: in <module>
    from .. import rb_multiarray
E   ImportError: dlopen(/Users/drapp/sandbox/redblackgraph/redblackgraph/rb_multiarray.cpython-36m-darwin.so, 2): Symbol not found: _int_avos
E     Referenced from: /Users/drapp/sandbox/redblackgraph/redblackgraph/rb_multiarray.cpython-36m-darwin.so
E     Expected in: flat namespace
E    in /Users/drapp/sandbox/redblackgraph/redblackgraph/rb_multiarray.cpython-36m-darwin.so

During handling of the above exception, another exception occurred:
tests/util/test_relationship_file_io.py:3: in <module>
    import redblackgraph as rb
redblackgraph/__init__.py:6: in <module>
    from . import core
redblackgraph/core/__init__.py:17: in <module>
    raise ImportError(msg)
E   ImportError: 
E   Importing the multiarray redblackgraph extension module failed.  Most
E   likely you are trying to import a failed build of redblackgraph.
E   If you're working with a git repo, try `git clean -xdf` (removes all
E   files not under version control).  Otherwise reinstall redblackgraph.
E   
E   Original error was: dlopen(/Users/drapp/sandbox/redblackgraph/redblackgraph/rb_multiarray.cpython-36m-darwin.so, 2): Symbol not found: _int_avos
E     Referenced from: /Users/drapp/sandbox/redblackgraph/redblackgraph/rb_multiarray.cpython-36m-darwin.so
E     Expected in: flat namespace
E    in /Users/drapp/sandbox/redblackgraph/redblackgraph/rb_multiarray.cpython-36m-darwin.so[0m

---------- coverage: platform darwin, python 3.6.4-final-0 -----------
Name                                           Stmts   Miss  Cover   Missing
----------------------------------------------------------------------------
redblackgraph/__init__.py                          9      5    44%   7-12
redblackgraph/core/__init__.py                    15      8    47%   7, 19-26
redblackgraph/core/avos_einsumfunc.py             11     11     0%   1-15
redblackgraph/core/rbm.py                          0      0   100%
redblackgraph/core/redblack.py                    74     74     0%   1-124
redblackgraph/reference/__init__.py                9      9     0%   1-9
redblackgraph/reference/avos.py                   18     18     0%   1-36
redblackgraph/reference/calc_relationship.py      23     23     0%   1-51
redblackgraph/reference/components.py             23     23     0%   1-34
redblackgraph/reference/generation.py              9      9     0%   1-18
redblackgraph/reference/mat_avos.py                5      5     0%   1-8
redblackgraph/reference/rel_composition.py        27     27     0%   1-50
redblackgraph/reference/triangularization.py      58     58     0%   1-108
redblackgraph/reference/util.py                   17     17     0%   1-40
redblackgraph/reference/vec_avos.py                5      5     0%   1-7
redblackgraph/reference/warshall.py               17     17     0%   1-27
redblackgraph/util/__init__.py                     1      1     0%   1
redblackgraph/util/relationship_file_io.py       118    118     0%   11-174
----------------------------------------------------------------------------
TOTAL                                            439    428     3%

[31m[1mFAIL Required test coverage of 80% not reached. Total coverage: 2.51%
[0m!!!!!!!!!!!!!!!!!!! Interrupted: 11 errors during collection !!!!!!!!!!!!!!!!!!!
[31m[1m=========================== 11 error in 0.95 seconds ===========================[0m
